DROP TABLE IF EXISTS appliance_models CASCADE;
DROP TABLE IF EXISTS appliance CASCADE;
DROP TABLE IF EXISTS model CASCADE;

CREATE TABLE IF NOT EXISTS appliance
(
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(255) NOT NULL,
    country              VARCHAR(255) NOT NULL,
    manufacturer         VARCHAR(255) NOT NULL,
    is_online_order      BOOLEAN      NOT NULL,
    installment          BOOLEAN      NOT NULL,
    appliance_attributes text         NOT NULL
);

CREATE TABLE IF NOT EXISTS model
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(50)                   NOT NULL,
    serial_number    VARCHAR(50)                   NOT NULL,
    color            VARCHAR(30)                   NOT NULL,
    price            NUMERIC(10, 2)                NOT NULL,
    size             NUMERIC(10, 2)                NOT NULL,
    is_available     BOOLEAN                       NOT NULL,
    appliance_id     INT REFERENCES appliance (id) NOT NULL,
    model_attributes text                          NOT NULL
);

