DROP TABLE IF EXISTS appliance_models CASCADE;
DROP TABLE IF EXISTS appliance CASCADE;
DROP TABLE IF EXISTS model CASCADE;

CREATE TABLE IF NOT EXISTS appliance
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    country         VARCHAR(255) NOT NULL,
    manufacturer    VARCHAR(255) NOT NULL,
    is_online_order BOOLEAN NOT NULL,
    installment     BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS model
(
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(50) NOT NULL,
    serial_number      VARCHAR(50) NOT NULL,
    color              VARCHAR(30) NOT NULL,
    price              NUMERIC(10, 2) NOT NULL,
    size               NUMERIC(10, 2) NOT NULL,
    is_available       BOOLEAN NOT NULL,
    appliance_id       INT REFERENCES appliance (id) NOT NULL,
    pc_category        VARCHAR(100),
    pc_processor_type  VARCHAR(100),
    f_doors_number     INT,
    f_compressor_type  VARCHAR(100),
    p_memory           INT,
    p_cameras_number   INT,
    tv_category        VARCHAR(100),
    tv_technology      VARCHAR(100),
    vc_dust_bag_volume NUMERIC(10, 2),
    vc_modes_number    NUMERIC(10, 2)
);

